username: "linkedin_email"
password: "linkedin_password"
phone_number: "mob. no"

positions:
- AWS Devops 
- aws Devpos Engineer
- aws Cloud
#- sre
#- Site reliablility # Another position you want to search for
#- A third position you want to search for
# Add any profile usin a "-" sign and comment the one you don't want to

locations:
#- Remote
#- India
#- Delhi
#- Noida
#- Gurugram
- us
- canada
- germany
- uk
- eu
- Netherlands
- turkey
- singapore
- qatar
- dubai
- kuwait


- # A second location you want to search in 

# --------- Optional Parameters -------
# uploads:
# Resume: "pasth to resume if not already uploaded on linkedin"
#  Cover Letter: # PATH TO cover letter
#  Photo: # PATH TO photo


# output_filename:
# - # PATH TO OUTPUT FILE (default output.csv)

# blacklist:
# - # Company names you want to ignore

#blackListTitles:
#- # Add job titles you want to ignore
